"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.auto = exports.reverse = exports.patch = exports.diff = void 0;
const diff_1 = require("./diff");
Object.defineProperty(exports, "diff", { enumerable: true, get: function () { return diff_1.diff; } });
const patch_1 = require("./patch");
Object.defineProperty(exports, "patch", { enumerable: true, get: function () { return patch_1.patch; } });
const reverse_1 = require("./reverse");
Object.defineProperty(exports, "reverse", { enumerable: true, get: function () { return reverse_1.reverse; } });
const auto_1 = require("./auto");
const auto = auto_1.AutoPigeon;
exports.auto = auto;
